**NUMPY LIBRERY**

In [1]:
import numpy as np

In [ ]:
print(np.__version__)

1.26.4


In [ ]:
myArray=np.array([1,2,3,4,5])
print(myArray)

[1 2 3 4 5]


In [ ]:
print(type(myArray))

<class 'numpy.ndarray'>


In [ ]:
print(myArray.shape)
print(myArray[2])
myArray[2] = 29
print(myArray)

(5,)
3
[ 1  2 29  4  5]


In [ ]:
myArray1=np.array([[1,2,3],[4,5,6]])
print(myArray1)
print(myArray1.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
myArray3=np.zeros((5,5))
print(myArray3)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
myArray4=np.full((3,6),10)
print(myArray4)
myArray5=np.eye(5)
print(myArray5)
myArray6=np.ones((5,5))
print(myArray6)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
myArray7=np.random.random((5,5))
print(myArray7)

[[0.58549421 0.26015747 0.41281742 0.55197374 0.23312415]
 [0.92081499 0.92488869 0.52485607 0.00168687 0.37806716]
 [0.85636294 0.15346054 0.98867973 0.18851181 0.24732045]
 [0.96398136 0.19741189 0.52095027 0.50776991 0.03149453]
 [0.00229702 0.53779917 0.02074938 0.71856974 0.92771049]]


In [ ]:
myArray8=np.random.randint(100,size=(5,5))
print(myArray8)

[[72 41 41 13  5]
 [12 71 13 14 84]
 [34 12 79 80 30]
 [46 64 43 77 95]
 [85 43 72 31 67]]


In [ ]:
newMatrix=myArray8[:2,:2]
print(newMatrix)

[[72 41]
 [12 71]]


In [ ]:
myArray8[2,2]=10000
print(myArray8)

[[   72    41    41    13     5]
 [   12    71    13    14    84]
 [   34    12 10000    80    30]
 [   46    64    43    77    95]
 [   85    43    72    31    67]]


In [ ]:
print(myArray8[2,:])

[   34    12 10000    80    30]


In [ ]:
print(myArray8[:,2])

[   41    13 10000    43    72]


In [ ]:
print(myArray8[:,2] .shape)

(5,)


In [ ]:
subMatrix=myArray8[1:4,1:4]
print(subMatrix)

[[   71    13    14]
 [   12 10000    80]
 [   64    43    77]]


**Martes 05/11/2024**




In [ ]:
#
import numpy as np
matrixA=np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(matrixA.shape)

(3, 4)


In [ ]:
matrixA

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [ ]:
print(matrixA[1:,1:3])

[[22 23]
 [32 33]]


In [ ]:
# Create a 4x3 matrix of random integers
matrixB = np.random.randint(0, 10, size=(4, 3))  # Generates random integers between 0 and 99 (inclusive)

print(matrixB)
print(matrixB.shape)

[[6 7 6]
 [5 1 1]
 [2 2 5]
 [1 8 4]]
(4, 3)


In [ ]:
print(matrixB)
col_indices=np.array([0,1,2])
fil_indices=np.array([1,2])

for fil,col in zip(fil_indices,col_indices):
  # print(fil," - ",col)
  print(matrixB[col,fil])
print(col_indices)
print(fil_indices)

[[8 8 7]
 [2 6 3]
 [3 3 0]
 [9 6 4]]
8
3
[0 1 2]
[1 2]


In [ ]:
mask=matrixB>7
print(mask)

[[ True  True  True]
 [ True False False]
 [False False  True]
 [False  True  True]]


In [ ]:
print(matrixB[mask])

[106 107 106 105 105 108 104]


In [ ]:
print(matrixB[matrixB>7])

[106 107 106 105 105 108 104]


In [ ]:
matrixB[matrixB % 2 == 0] += 100

matrixB

array([[108, 108,   7],
       [102, 106,   3],
       [  3,   3, 100],
       [  9, 106, 104]])

In [ ]:
filter=(matrixB>3) & (matrixB<9)
matrixB[filter]+=100
print(matrixB)

[[106 107 106]
 [105   1   1]
 [  2   2 105]
 [  1 108 104]]


In [ ]:
matrixA1 = np.random.randint(0, 10, size=(2, 2))
matrixA2 = np.random.randint(0, 10, size=(2, 2))
print("MatrixA1")
print(matrixA1)
print("MatrixA2")
print(matrixA2)

MatrixA1
[[5 4]
 [0 6]]
MatrixA2
[[0 0]
 [0 9]]


In [ ]:
print("SUMA")
print(matrixA1+matrixA2)
print("RESTA")
print(matrixA1-matrixA2)
print("MULTIPLICACIÓN")
print(matrixA1*matrixA2)
print("DIVISIÓN")
print(matrixA1/matrixA2)

SUMA
[[ 5  4]
 [ 0 15]]
RESTA
[[ 5  4]
 [ 0 -3]]
MULTIPLICACIÓN
[[ 0  0]
 [ 0 54]]
DIVISIÓN
[[       inf        inf]
 [       nan 0.66666667]]


<ipython-input-105-98f3e5b13117>:8: RuntimeWarning: divide by zero encountered in divide
  print(matrixA1/matrixA2)
<ipython-input-105-98f3e5b13117>:8: RuntimeWarning: invalid value encountered in divide
  print(matrixA1/matrixA2)


In [ ]:
print(matrixA1)

[[5 4]
 [0 6]]


In [ ]:
print(np.sqrt(matrixA1))

[[2.23606798 2.        ]
 [0.         2.44948974]]


In [ ]:
matrixA1 = np.random.randint(0, 10, size=(2, 5))
print(matrixA1)


[[1 9 2 0 0]
 [6 8 9 2 7]]


In [ ]:
print(np.mean(matrixA1))

5.4


In [ ]:
print(matrixA1.mean(axis=1))

[6.2 4.6]


In [ ]:
print(matrixA1.mean(axis=0))

[6.5 2.5 7.5 5.  5.5]


In [ ]:
print(np.std(matrixA1))

3.5552777669262356


In [ ]:
print(np.median(matrixA1))

4.0


In [ ]:
print(matrixA1.sum())

44


In [ ]:
print(np.max(matrixA1))

9


In [ ]:
print(np.min(matrixA1))

0


In [9]:
start=np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
add_rows=np.array([1,2,3])
print(add_rows.shape)

(3,)


In [10]:
y=start+add_rows
print(y)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [11]:
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
col_rows=np.array([[1,2,3,4]])
col_rows=col_rows.T
print(col_rows)
y2=start+col_rows
print(y2)

[[1]
 [2]
 [3]
 [4]]
[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]]


In [ ]:
tmp1=np.array([[1,1],[2,2]])
print(tmp1)
tmp2=np.array([[3,3],[4,4]])
print(tmp2)

[[1 1]
 [2 2]]
[[3 3]
 [4 4]]


In [ ]:
print(np.dot(tmp1,tmp2))

[[ 7  7]
 [14 14]]


In [ ]:
y1=np.random.randint(low=2,high=50,size=(2,2))
y2=np.random.randint(low=2,high=50,size=(2,2))
print(y1)
print(y2)

[[19 26]
 [34 23]]
[[11 27]
 [26  8]]
